#!/usr/bin/env python3
"""
make_fixtures.py — build two local fixture sites for testing the marketplace.

  bad/   a deliberately broken site (blocked AI crawlers, JS shell, invalid
         JSON-LD, PDF-only pricing, soft 404, stale copyright, no alt text)
  good/  a clean equivalent that should produce ZERO defect findings

The clean site is the more important of the two: it is the false-positive
control. A check that fires on it is wrong, regardless of how sensible it
looked when written.

Usage:
  python3 make_fixtures.py [--dir ./fixtures]
  cd fixtures/bad  && python3 -m http.server 8800
  cd fixtures/good && python3 -m http.server 8801
"""

import argparse
import os

FILES = {
    "bad/about.html": "<!doctype html><html><head><title>About</title></head><body>\n<main><h1>About</h1><img src=\"/team.png\"><img src=\"/chart-of-prices.png\" alt=\"chart.png\">\n<p>We do things.</p></main><footer>&copy; 2019 Vertex</footer></body></html>\n",
    "bad/index.html": "<!doctype html><html><head><title>Home</title>\n<script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Organization\",\"name\":\"YOUR_COMPANY_NAME\",}</script>\n<script src=\"/a.js\"></script><script src=\"/b.js\"></script><script src=\"/c.js\"></script>\n</head><body><div id=\"root\"></div>\n<noscript>Please enable JavaScript.</noscript>\n<a href=\"/pricing.html\">Pricing</a><a href=\"/about.html\">About</a><a href=\"/gone.html\">Docs</a>\n<a href=\"/rates.pdf\">Download rate card (PDF)</a>\n</body></html>\n",
    "bad/notfound.html": "<!doctype html><html><head><title>404 Error</title></head><body><main><h1>Page not found</h1><p>Sorry, we couldn't find that page.</p></main></body></html>\n",
    "bad/pricing.html": "<!doctype html><html><head><title>Pricing</title><link rel=\"canonical\" href=\"https://someoneelse.example/pricing\"></head>\n<body><div id=\"app\"></div><script src=\"/x.js\"></script><script src=\"/y.js\"></script><script src=\"/z.js\"></script></body></html>\n",
    "bad/rates.pdf": "x",
    "bad/robots.txt": "User-agent: GPTBot\nDisallow: /\n\nUser-agent: ClaudeBot\nDisallow: /\n\nUser-agent: PerplexityBot\nDisallow: /\n\nUser-agent: CCBot\nDisallow: /\n\nUser-agent: *\nDisallow: /wp-admin\nDisallow: /pricing\n",
    "good/about.html": "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Northwind Analytics \u2014 supply-chain forecasting for mid-market retailers</title>\n<meta name=\"description\" content=\"Northwind Analytics is a Bristol-based software company providing demand-forecasting tools for mid-market retailers.\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<link rel=\"canonical\" href=\"http://127.0.0.1:8801/about.html\">\n<script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Organization\",\"@id\":\"http://127.0.0.1:8801/#org\",\"name\":\"Northwind Analytics Ltd\",\"alternateName\":\"Northwind Analytics\",\"url\":\"http://127.0.0.1:8801/\",\"foundingDate\":\"2016\",\"description\":\"Demand-forecasting software for mid-market retailers.\",\"address\":{\"@type\":\"PostalAddress\",\"addressLocality\":\"Bristol\",\"addressCountry\":\"GB\"},\"areaServed\":\"GB\",\"sameAs\":[\"http://127.0.0.1:8801/profile.html\"]}</script>\n</head><body>\n<nav><a href=\"/index.html\">Home</a> <a href=\"/about.html\">About</a> <a href=\"/pricing.html\">Pricing</a> <a href=\"/contact.html\">Contact</a></nav>\n<main><h1>About Northwind Analytics</h1>\n<p>Northwind Analytics Ltd is a Bristol-based software company that provides demand-forecasting tools for mid-market retailers with 10 to 200 stores. Founded in 2016, it serves customers across the United Kingdom.</p>\n<h2>What it does</h2><p>The platform ingests point-of-sale data and produces weekly replenishment forecasts at SKU and store level, typically reducing stockouts within one quarter of deployment.</p>\n<h2>Who it is for</h2><p>Retail operations teams responsible for buying and replenishment across ten or more physical stores.</p>\n<h2>How much it costs</h2><p>Plans start at \u00a3450 per month for up to 25 stores. See the pricing page for the full breakdown.</p>\n<h2>How to get started</h2><p>Book a 30-minute demo, or email hello@northwind.example to speak to the team.</p>\n<figure><img src=\"/dash.png\" alt=\"Forecast dashboard showing weekly SKU-level replenishment for 25 stores\" width=\"600\" height=\"400\"><figcaption>Weekly replenishment view.</figcaption></figure>\n<p><a href=\"/contact.html\">Book a demo</a></p></main>\n<footer><p>Northwind Analytics Ltd, 14 Queen Square, Bristol BS1 4NX, United Kingdom. hello@northwind.example. &copy; 2026.</p></footer></body></html>\n",
    "good/contact.html": "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Northwind Analytics \u2014 supply-chain forecasting for mid-market retailers</title>\n<meta name=\"description\" content=\"Northwind Analytics is a Bristol-based software company providing demand-forecasting tools for mid-market retailers.\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<link rel=\"canonical\" href=\"http://127.0.0.1:8801/contact.html\">\n<script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Organization\",\"@id\":\"http://127.0.0.1:8801/#org\",\"name\":\"Northwind Analytics Ltd\",\"alternateName\":\"Northwind Analytics\",\"url\":\"http://127.0.0.1:8801/\",\"foundingDate\":\"2016\",\"description\":\"Demand-forecasting software for mid-market retailers.\",\"address\":{\"@type\":\"PostalAddress\",\"addressLocality\":\"Bristol\",\"addressCountry\":\"GB\"},\"areaServed\":\"GB\",\"sameAs\":[\"http://127.0.0.1:8801/profile.html\"]}</script>\n</head><body>\n<nav><a href=\"/index.html\">Home</a> <a href=\"/about.html\">About</a> <a href=\"/pricing.html\">Pricing</a> <a href=\"/contact.html\">Contact</a></nav>\n<main><h1>Contact</h1>\n<p>Northwind Analytics Ltd is a Bristol-based software company that provides demand-forecasting tools for mid-market retailers with 10 to 200 stores. Founded in 2016, it serves customers across the United Kingdom.</p>\n<h2>What it does</h2><p>The platform ingests point-of-sale data and produces weekly replenishment forecasts at SKU and store level, typically reducing stockouts within one quarter of deployment.</p>\n<h2>Who it is for</h2><p>Retail operations teams responsible for buying and replenishment across ten or more physical stores.</p>\n<h2>How much it costs</h2><p>Plans start at \u00a3450 per month for up to 25 stores. See the pricing page for the full breakdown.</p>\n<h2>How to get started</h2><p>Book a 30-minute demo, or email hello@northwind.example to speak to the team.</p>\n<figure><img src=\"/dash.png\" alt=\"Forecast dashboard showing weekly SKU-level replenishment for 25 stores\" width=\"600\" height=\"400\"><figcaption>Weekly replenishment view.</figcaption></figure>\n<p><a href=\"/contact.html\">Book a demo</a></p></main>\n<footer><p>Northwind Analytics Ltd, 14 Queen Square, Bristol BS1 4NX, United Kingdom. hello@northwind.example. &copy; 2026.</p></footer></body></html>\n",
    "good/index.html": "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Northwind Analytics \u2014 supply-chain forecasting for mid-market retailers</title>\n<meta name=\"description\" content=\"Northwind Analytics is a Bristol-based software company providing demand-forecasting tools for mid-market retailers.\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<link rel=\"canonical\" href=\"http://127.0.0.1:8801/index.html\">\n<script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Organization\",\"@id\":\"http://127.0.0.1:8801/#org\",\"name\":\"Northwind Analytics Ltd\",\"alternateName\":\"Northwind Analytics\",\"url\":\"http://127.0.0.1:8801/\",\"foundingDate\":\"2016\",\"description\":\"Demand-forecasting software for mid-market retailers.\",\"address\":{\"@type\":\"PostalAddress\",\"addressLocality\":\"Bristol\",\"addressCountry\":\"GB\"},\"areaServed\":\"GB\",\"sameAs\":[\"http://127.0.0.1:8801/profile.html\"]}</script>\n</head><body>\n<nav><a href=\"/index.html\">Home</a> <a href=\"/about.html\">About</a> <a href=\"/pricing.html\">Pricing</a> <a href=\"/contact.html\">Contact</a></nav>\n<main><h1>Northwind Analytics</h1>\n<p>Northwind Analytics Ltd is a Bristol-based software company that provides demand-forecasting tools for mid-market retailers with 10 to 200 stores. Founded in 2016, it serves customers across the United Kingdom.</p>\n<h2>What it does</h2><p>The platform ingests point-of-sale data and produces weekly replenishment forecasts at SKU and store level, typically reducing stockouts within one quarter of deployment.</p>\n<h2>Who it is for</h2><p>Retail operations teams responsible for buying and replenishment across ten or more physical stores.</p>\n<h2>How much it costs</h2><p>Plans start at \u00a3450 per month for up to 25 stores. See the pricing page for the full breakdown.</p>\n<h2>How to get started</h2><p>Book a 30-minute demo, or email hello@northwind.example to speak to the team.</p>\n<figure><img src=\"/dash.png\" alt=\"Forecast dashboard showing weekly SKU-level replenishment for 25 stores\" width=\"600\" height=\"400\"><figcaption>Weekly replenishment view.</figcaption></figure>\n<p><a href=\"/contact.html\">Book a demo</a></p></main>\n<footer><p>Northwind Analytics Ltd, 14 Queen Square, Bristol BS1 4NX, United Kingdom. hello@northwind.example. &copy; 2026.</p></footer></body></html>\n",
    "good/pricing.html": "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Northwind Analytics \u2014 supply-chain forecasting for mid-market retailers</title>\n<meta name=\"description\" content=\"Northwind Analytics is a Bristol-based software company providing demand-forecasting tools for mid-market retailers.\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<link rel=\"canonical\" href=\"http://127.0.0.1:8801/pricing.html\">\n<script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Organization\",\"@id\":\"http://127.0.0.1:8801/#org\",\"name\":\"Northwind Analytics Ltd\",\"alternateName\":\"Northwind Analytics\",\"url\":\"http://127.0.0.1:8801/\",\"foundingDate\":\"2016\",\"description\":\"Demand-forecasting software for mid-market retailers.\",\"address\":{\"@type\":\"PostalAddress\",\"addressLocality\":\"Bristol\",\"addressCountry\":\"GB\"},\"areaServed\":\"GB\",\"sameAs\":[\"http://127.0.0.1:8801/profile.html\"]}</script>\n</head><body>\n<nav><a href=\"/index.html\">Home</a> <a href=\"/about.html\">About</a> <a href=\"/pricing.html\">Pricing</a> <a href=\"/contact.html\">Contact</a></nav>\n<main><h1>Pricing</h1>\n<p>Northwind Analytics Ltd is a Bristol-based software company that provides demand-forecasting tools for mid-market retailers with 10 to 200 stores. Founded in 2016, it serves customers across the United Kingdom.</p>\n<h2>What it does</h2><p>The platform ingests point-of-sale data and produces weekly replenishment forecasts at SKU and store level, typically reducing stockouts within one quarter of deployment.</p>\n<h2>Who it is for</h2><p>Retail operations teams responsible for buying and replenishment across ten or more physical stores.</p>\n<h2>How much it costs</h2><p>Plans start at \u00a3450 per month for up to 25 stores. See the pricing page for the full breakdown.</p>\n<h2>How to get started</h2><p>Book a 30-minute demo, or email hello@northwind.example to speak to the team.</p>\n<figure><img src=\"/dash.png\" alt=\"Forecast dashboard showing weekly SKU-level replenishment for 25 stores\" width=\"600\" height=\"400\"><figcaption>Weekly replenishment view.</figcaption></figure>\n<p><a href=\"/contact.html\">Book a demo</a></p></main>\n<footer><p>Northwind Analytics Ltd, 14 Queen Square, Bristol BS1 4NX, United Kingdom. hello@northwind.example. &copy; 2026.</p></footer></body></html>\n",
    "good/profile.html": "<!doctype html><html lang=\"en\"><head><title>Northwind Analytics Ltd \u2014 company profile</title></head><body><main><h1>Northwind Analytics Ltd</h1><p>Northwind Analytics Ltd is a Bristol-based software company providing demand-forecasting tools for mid-market retailers. Website: http://127.0.0.1:8801/</p></main></body></html>\n",
    "good/robots.txt": "User-agent: *\nDisallow: /cart\nDisallow: /admin\nDisallow: /search?\nAllow: /\n\nSitemap: http://127.0.0.1:8801/sitemap.xml\n",
    "good/sitemap.xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n<url><loc>http://127.0.0.1:8801/index.html</loc><lastmod>2026-08-01</lastmod></url>\n<url><loc>http://127.0.0.1:8801/about.html</loc><lastmod>2026-08-01</lastmod></url>\n<url><loc>http://127.0.0.1:8801/pricing.html</loc><lastmod>2026-08-12</lastmod></url>\n</urlset>\n",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="fixtures")
    args = ap.parse_args()
    for rel, content in FILES.items():
        path = os.path.join(args.dir, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print("wrote", path)
    print("\nServe them:")
    print(f"  (cd {args.dir}/bad  && python3 -m http.server 8800) &")
    print(f"  (cd {args.dir}/good && python3 -m http.server 8801) &")


if __name__ == "__main__":
    main()
